// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFui9ST5zjiVp6SyVvz3T3fcyzqW0hCFM',
    appId: '1:37107639852:web:a670f915819926a49e9389',
    messagingSenderId: '37107639852',
    projectId: 'uniaccess-27506',
    authDomain: 'uniaccess-27506.firebaseapp.com',
    storageBucket: 'uniaccess-27506.firebasestorage.app',
    measurementId: 'G-E7H6S0QMVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKN4IXL0PBMlBBTU7wEIzAQRNKCXHNQpI',
    appId: '1:37107639852:android:ed0c0059b7636a959e9389',
    messagingSenderId: '37107639852',
    projectId: 'uniaccess-27506',
    storageBucket: 'uniaccess-27506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5tsYvaIdMer-Vx7ssKiw3qsXiuL_UOms',
    appId: '1:37107639852:ios:eab1c480b11e82d09e9389',
    messagingSenderId: '37107639852',
    projectId: 'uniaccess-27506',
    storageBucket: 'uniaccess-27506.firebasestorage.app',
    iosBundleId: 'com.example.uniaccess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5tsYvaIdMer-Vx7ssKiw3qsXiuL_UOms',
    appId: '1:37107639852:ios:eab1c480b11e82d09e9389',
    messagingSenderId: '37107639852',
    projectId: 'uniaccess-27506',
    storageBucket: 'uniaccess-27506.firebasestorage.app',
    iosBundleId: 'com.example.uniaccess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFui9ST5zjiVp6SyVvz3T3fcyzqW0hCFM',
    appId: '1:37107639852:web:a5cc122444516c079e9389',
    messagingSenderId: '37107639852',
    projectId: 'uniaccess-27506',
    authDomain: 'uniaccess-27506.firebaseapp.com',
    storageBucket: 'uniaccess-27506.firebasestorage.app',
    measurementId: 'G-6KYGL702M7',
  );
}
